version: '3'
services:
  app:
    build: .
    ports:
      - "${DOCKER_PORT}:3000"
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - NODE_ENV=production
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
        - MYSQL_ROOT_PASSWORD=${DB_PASS}
        - MYSQL_DATABASE=${DB_NAME}
    volumes:
    - ./db:/var/lib/mysql