services:
  app:
    container_name: habapay-api-app
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    ports:
      - "3003:3000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: habapay-api-db
    image: mysql:5.7
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1m30s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes:
  db_data:
